name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # update tiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate contribution snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: adityaalif-1011   # GANTI jika username beda
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit generated SVG to 'output' branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update contribution snake"
          add: "dist/**"
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
